### ISSUE TITLE
Suggestion: Can we have a config to decide moving reactions to the left or right?

### ISSUE THREAD

**Issue by suyanhanx** [patak-dev/refined-github-reactions#3]
Thanks for your great work!

But it‘s just that I'm getting pretty used to putting reactions on the left.
I'm sure many users feel the same way.

**Comment by patak-cat** [comment]
Hey! The issue with having it on the left is that it would generally look quite cramped with the last line of text.
The style overrides are only a few lines of code, feel free to fork it and modify it to feet your needs. I would be keeping this one opinionated to avoid maintenance overhead.
