### ISSUE TITLE
Merge in to Refined GitHub

### ISSUE THREAD

**Issue by uncenter** [patak-dev/refined-github-reactions#7]
Have you tried upstreaming/merging this styling into Refined GitHub itself? I love this userscript but I think it would be more helpful built into the extension :)

**Comment by patak-cat** [comment]
I'd love if this would be part of Refined GitHub, I don't have the time right now to do that though. If someone would like to contribute it to Refined and help maintain it there, I'm more than happy to add a note redirecting people to use that instead.
